source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'MockingPlace_Example', :exclusive => true do
  pod "MockingPlace", :path => "../"
end

target 'MockingPlace_Tests', :exclusive => true do
  pod "MockingPlace", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
