/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreLocation.framework/CoreLocation
 */

@import CoreLocation;

@interface CLHeading (Init)

- (id)initWithHeading:(double)heading accuracy:(double)accuracy;

@end
